### ISSUE TITLE
Link error after upgrade to 4.6.1

### ISSUE THREAD

**Issue by Pylipala** [react-native-community/react-native-svg#220]
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNSVGPathParser", referenced from:
      objc-class-ref in libRNSVG.a(RCTConvert+RNSVG.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by Pylipala** [comment]
Oh, I should reopen XCode after upgrading. XCode will not auto load added files.
