### ISSUE TITLE
react-native-web jest error

### ISSUE THREAD

**Issue by thorakmedichi** [react-native-community/react-native-svg#995]
"react": "^16.8.4",
"react-native": "0.55.4",
"react-native-web": "^0.9.x",  /// NOTE: using RNW
"react-native-svg": "6.0.0",

react-native-svg seems to be working fine for Android and Web so far but when running my Jest test I am getting the following error

```
● Test suite failed to run

TypeError: (0 , _reactNativeWeb.requireNativeComponent) is not a function

  1 | import React from 'react';
  2 |
> 3 | import Svg, { Path, Rect } from 'react-native-svg';
    | ^
  4 |
  5 | import { numPropType, stringPropType } from '../../prop-types/propTypes';
  6 |

  at Object.<anonymous> (node_modules/react-native-svg/elements/Svg.js:99:23)
  at Object.<anonymous> (node_modules/react-native-svg/index.js:7:1)
  at Object.<anonymous> (src/common/assets/edit-log-icons/clone-icon.js:3:1)
```

I tried to mock react-native-svg but it doesn't seem to be working. I tried react-native-svg-mock to no avail and I also tried several different variations online. The most current of which is

```
jest.mock('react-native-svg', () => {
    const React = require('react');
    const ReactNativeSvg = jest.genMockFromModule('react-native-svg');

    const svgElementMockGenerator = (name, propTypes) => {
        function SvgMock() {
            return (
                React.createElement(name, null, null)
            )
        }

        SvgMock.displayName = name
        SvgMock.propTypes = propTypes

        return SvgMock
    };

    const Svg = svgElementMockGenerator('Svg', ReactNativeSvg.Svg.propTypes);

    Svg.Rect = svgElementMockGenerator('Rect', ReactNativeSvg.Rect.propTypes);
    Svg.LinearGradient = svgElementMockGenerator(
        'LinearGradient',
        ReactNativeSvg.LinearGradient.propTypes
    );
    Svg.Path = svgElementMockGenerator('Path', ReactNativeSvg.Path.propTypes);
    Svg.Symbol = svgElementMockGenerator('Symbol', ReactNativeSvg.Symbol.propTypes);
    Svg.Use = svgElementMockGenerator('Use', ReactNativeSvg.Use.propTypes);
    Svg.Stop = svgElementMockGenerator('Stop', ReactNativeSvg.Stop.propTypes);
    Svg.Defs = svgElementMockGenerator('Defs', ReactNativeSvg.Defs.propTypes);

    return Svg;
});
```
using this mock seems to make the error SLIGHTLY different, in that it doesn't point to the import. 

```
● Test suite failed to run

TypeError: (0 , _reactNativeWeb.requireNativeComponent) is not a function

  at Object.<anonymous> (node_modules/react-native-svg/elements/Svg.js:146:64)
  at Object.<anonymous> (node_modules/react-native-svg/index.js:142:35)
  at Object.user:/home/thorakmedichi/Development/Projects/myProject/node_modules/react-native-svg/index.js: (config/initTest.js:16:29)
```

Any help would be appreciated.

**Comment by thorakmedichi** [comment]
Updated to "react-native-svg": "9.4.0" despite the docs saying to use 6.0.0. Solved my issues.

**Comment by thorakmedichi** [comment]
I thought I solved this with an upgrade from 6.0.0 to 9.4.0 but I was wrong.

Still looking for help on this issue

**Comment by Sliverb** [comment]
I just started looking into this lib so not sure how much help this is, but in my research I ran into https://github.com/bakerface/react-native-svg-web which called out acting as a drop in for web and jest. Good luck and hope it helps. I'll circle back when I learn more

**Comment by joan-saum** [comment]
@thorakmedichi, for me, it's even not working for Web. I got a JS error saying `requireNativeComponent is not a function` :/

**Comment by MillerGregor** [comment]
as @Sliverb suggested, [bakerface/react-native-svg-web](https://github.com/bakerface/react-native-svg-web)  fixed my jest tests... but ` jest.mock() ` didn't work for me.

I had to make two additions to my jest config:

```
{
  moduleNameMapper: {
    'react-native-svg': 'react-native-svg-web',
  },
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|react-native-svg-web|react-native-something-else)/)'
  ]
}
```

**Comment by kopax-polyconseil** [comment]
I just tried this configuration and I still have:

```
/node_modules/react-native-svg-web/index.js:23
    import * as React from "react";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import * as React from 'react'
    > 2 | import Svg, { Path } from 'react-native-svg'
        | ^
      3 | import { IconProps, mapIconPropsToSvgProps } from './types'
      4 | 

```

I am in a monorepo lerna, I don't think that might be related but worth to be said.

**Comment by tkrotoff** [comment]
This issue should not be closed.

Same problem with Jest and a react-native-web application:

```
 FAIL  src/features/Course/ReportPlus/ReportPlusContainer/index.test.tsx
  ● Test suite failed to run

    TypeError: (0 , _reactNative.requireNativeComponent) is not a function

      1 | import * as React from 'react';
    > 2 | import Svg, { SvgProps, Path } from 'react-native-svg';
        | ^
      3 |
      4 | const SvgPictoReplayCourse = (props: SvgProps) => (
      5 |   <Svg width="8" height="8" viewBox="0 0 8 8" {...props}>

      at Object.<anonymous> (node_modules/react-native-svg/lib/commonjs/elements/NativeComponents.tsx:3:25)
      at Object.<anonymous> (node_modules/react-native-svg/lib/commonjs/elements/Rect.tsx:5:1)
      at Object.<anonymous> (node_modules/react-native-svg/lib/commonjs/ReactNativeSVG.ts:2:1)
      at Object.<anonymous> (node_modules/react-native-svg/lib/commonjs/index.ts:1:1)
      at Object.<anonymous> (assets/icons/PictoReplayCourse.tsx:2:1)
      ...
```

Using react-native-svg 12.3.0 & react-native-web 0.16.3

**Comment by kopax-polyconseil** [comment]
I have the same issue after upgrading jest to v28.

**Comment by merrywhether** [comment]
At least for us, Jest doesn't natively find the `.web.ts` build (still new to RN and grokking these platform-specific build files), so we configured that manually in our jest config (but this was the only necessary change):
```
  moduleNameMapper: {
    '^react-native$': 'react-native-web',
    '^react-native-svg$': 'react-native-svg/lib/commonjs/ReactNativeSVG.web.js',
  },
```
Then you don't have to import the old `react-native-svg-web` files and can use the built-in support.

**Comment by QQizi** [comment]
Can't figure out how to get rid of the error. 
```
import * as React from "react";
    ^^^^^^
    SyntaxError: Cannot use import statement outside a module
