### ISSUE TITLE
cannot find symbol ReactShadowNodeImpl

### ISSUE THREAD

**Issue by dansmog** [react-native-community/react-native-svg#693]
After successfully installing and link react-native-svg to my app, running react-native run-android, i get the below error

``` /home/squarelabs/Project/Bubble/node_modules/react-native-svg/android/src/main/java/com/horcrux   /svg/SvgView.java:23: error: cannot find symbol
import com.facebook.react.uimanager.ReactShadowNodeImpl;
                                   ^
  symbol:   class ReactShadowNodeImpl
  location: package com.facebook.react.uimanager
/home/squarelabs/Project/Bubble/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgView.java:109: error: cannot find symbol
        ReactShadowNodeImpl node = getShadowNode();
        ^
  symbol:   class ReactShadowNodeImpl
  location: class SvgView
/home/squarelabs/Project/Bubble/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgView.java:115: error: cannot find symbol
                    ReactShadowNodeImpl nodeChild = node.getChildAt(j);
                    ^
  symbol:   class ReactShadowNodeImpl
  location: class SvgView ```

Am working with RN v 0.49

**Comment by ln0v** [comment]
pls check the version of react-native-svg that you installed. Version 5.4.1 support RN >= 0.47

**Comment by dansmog** [comment]
Thank you, have solved it by upgrading my react-native version.

**Comment by godofmadness** [comment]
Facing the same issue
react-native : "^0.49.5"
react-native-svg : "^6.4.1"

**Comment by jeffreyrajanofficial** [comment]
@godofmadness  You need to install 5.5.1 version instead of 6.4.1

Here is the list of version that supports

react-native-svg >= 3.2.0 only supports react-native >= 0.29.0
react-native-svg >= 4.2.0 only supports react-native >= 0.32.0
react-native-svg >= 4.3.0 only supports react-native >= 0.33.0
react-native-svg >= 4.4.0 only supports react-native >= 0.38.0 and react >= 15.4.0
react-native-svg >= 4.5.0 only supports react-native >= 0.40.0 and react >= 15.4.0
react-native-svg >= 5.1.8 only supports react-native >= 0.44.0 and react == 16.0.0-alpha.6
react-native-svg >= 5.2.0 only supports react-native >= 0.45.0 and react == 16.0.0-alpha.12
react-native-svg >= 5.3.0 only supports react-native >= 0.46.0 and react == 16.0.0-alpha.12
react-native-svg >= 5.4.1 only supports react-native >= 0.47.0 and react == 16.0.0-alpha.12
react-native-svg >= 5.5.1 only supports react-native >= 0.50.0 and react == 16.0.0

**Comment by top-master** [comment]
below command should help:
`npm install --save react-native-svg@5.5.1`
