### ISSUE TITLE
Typings issue 

### ISSUE THREAD

**Issue by toytonic** [react-native-community/react-native-svg#692]
When upgrading typescript to 2.8.3 I get the following issue in strict mode:

```
node_modules/react-native-svg/index.d.ts:269:18 - error TS2430: Interface 'SvgProps' incorrectly extends interface 'ViewProps'.
  Types of property 'opacity' are incompatible.
    Type 'string | number | undefined' is not assignable to type 'number | undefined'.
      Type 'string' is not assignable to type 'number | undefined'.

269 export interface SvgProps extends ReactNative.ViewProperties {
```

The problem is the `string` in the union type. Can be removed for opacity I guess...

**Comment by haitaox** [comment]
Having the same issue. any update?

**Comment by toytonic** [comment]
I created a pull request:
https://github.com/react-native-community/react-native-svg/pull/718

**Comment by msand** [comment]
Hmm, strings are valid inputs in this case https://github.com/react-native-community/react-native-svg/blob/master/lib/extract/extractOpacity.js#L2
But, if it's causing errors I guess it makes sense to change it. Is there any way to remove/override the inherited conflicting type from ViewProps in typescript? But I guess that doesn't make sense, as in that case it can't guarantee that other api:s expecting that type can handle it.
