### ISSUE TITLE
breaking change in 0.42?

### ISSUE THREAD

**Issue by ksegla** [react-native-community/react-native-svg#271]
Hi
After upgrading to 0.42?, I keep getting this for Android (I had no problems with 0.41)
___
...com\horcrux\svg\RNSVGImageShadowNode.java:195: error: no suitable method found for setWidth(float)
viewBox.setWidth(rectWidth / mScale);
^
method LayoutShadowNode.setWidth(Dynamic) is not applicable
(argument mismatch; float cannot be converted to Dynamic)
method RNSVGViewBoxShadowNode.setWidth(String) is not applicable
(argument mismatch; float cannot be converted to String)
____
same thing with setHeight

**Comment by ksegla** [comment]
I went to the file of the module and changed the module like this: viewBox.setWidth(""+(rectWidth / mScale)). same for setHeight. Problem solved. 
Feel free to close this but consider fixing it.

**Comment by magicismight** [comment]
You can upgrade `react-native-svg` to the latest version. It would fix this.
